Automatically retry EasyPost Shipment creation for common errors
Printavo/solidus_easypost pull request #4
Opened 2019-10-22 19:58 UTC by neelk07

TrackerUrl: https://www.pivotaltracker.com/story/show/167745836

2019-10-22 20:05 UTC, bengolden commented on app/models/spree/shipment_decorator.rb
> +        for_selected_rate = "#{rate.carrier} #{rate.service}" == self.selected_shipping_rate.name
it looks like this line is a duplicate of line 48 and not needed

2019-10-22 20:05 UTC, bengolden commented on app/models/spree/shipment_decorator.rb
> +      no_matches_found = []
this variable is unused

2019-10-22 20:07 UTC, PeteTheSadPanda requested changes

2019-10-22 20:07 UTC, PeteTheSadPanda commented on app/models/spree/shipment_decorator.rb
> +      rescue Exception => exception
RuntimeError, never rescue just Exception

2019-10-22 20:07 UTC, PeteTheSadPanda commented on app/models/spree/shipment_decorator.rb
> +        if old_rate.blank?
this seems like it's just if old_rate.blank? && for_selected_rate

2019-10-22 20:07 UTC, PeteTheSadPanda commented on app/models/spree/shipment_decorator.rb
> +        matches["#{old_rate.easy_post_rate_id}"] = rate.id
matches[old_rate.easy_post_rate_id.to_s]

2019-10-23 18:52 UTC, PeteTheSadPanda commented
Looks good. Merging.

2019-10-23 18:52 UTC, merged